// File: words.js (Database Kosakata Jerman A1 & A2 Lengkap)
const database = {
    "A1": [
        { article: "der", word: "Vater", plural: "die V*ä*t*er*", genitive: "-s", meaning: "Ayah", example: { de: "Mein Vater ist sehr nett.", id: "Ayahku sangat ramah." } },
        { article: "die", word: "Mutter", plural: "die M*ü*tter", genitive: "-", meaning: "Ibu", example: { de: "Meine Mutter kocht gut.", id: "Ibuku memasak dengan enak." } },
        { article: "der", word: "Sohn", plural: "die S*ö*hn*e*", genitive: "-es", meaning: "Anak Laki-laki", example: { de: "Das ist mein Sohn.", id: "Ini adalah anak laki-lakiku." } },
        { article: "die", word: "Tochter", plural: "die T*ö*cht*er*", genitive: "-", meaning: "Anak Perempuan", example: { de: "Sie hat eine Tochter.", id: "Dia punya seorang anak perempuan." } },
        { article: "der", word: "Bruder", plural: "die Br*ü*d*er*", genitive: "-s", meaning: "Saudara Laki-laki", example: { de: "Mein Bruder wohnt in Berlin.", id: "Saudara laki-lakiku tinggal di Berlin." } },
        { article: "die", word: "Schwester", plural: "die Schwester*n*", genitive: "-", meaning: "Saudara Perempuan", example: { de: "Ich habe zwei Schwestern.", id: "Saya punya dua saudara perempuan." } },
        { article: "der", word: "Opa", plural: "die Opa*s*", genitive: "-s", meaning: "Kakek", example: { de: "Mein Opa ist 80 Jahre alt.", id: "Kakekku berumur 80 tahun." } },
        { article: "die", word: "Oma", plural: "die Oma*s*", genitive: "-", meaning: "Nenek", example: { de: "Ich besuche meine Oma.", id: "Saya mengunjungi nenekku." } },
        { article: "der", word: "Onkel", plural: "die Onkel", genitive: "-s", meaning: "Paman", example: { de: "Mein Onkel arbeitet hier.", id: "Pamanku bekerja di sini." } },
        { article: "die", word: "Tante", plural: "die Tante*n*", genitive: "-", meaning: "Bibi", example: { de: "Meine Tante kommt heute.", id: "Bibiku datang hari ini." } },
        { article: "der", word: "Junge", plural: "die Junge*n*", genitive: "-n", meaning: "Anak Laki-laki", example: { de: "Der Junge spielt Fußball.", id: "Anak laki-laki itu bermain sepak bola." } },
        { article: "das", word: "Mädchen", plural: "die Mädchen", genitive: "-s", meaning: "Anak Perempuan", example: { de: "Das Mädchen liest ein Buch.", id: "Anak perempuan itu membaca buku." } },
        { article: "der", word: "Mann", plural: "die M*ä*nn*er*", genitive: "-es", meaning: "Pria / Suami", example: { de: "Der Mann ist groß.", id: "Pria itu tinggi." } },
        { article: "die", word: "Frau", plural: "die Frau*en*", genitive: "-", meaning: "Wanita / Istri", example: { de: "Die Frau trinkt Kaffee.", id: "Wanita itu minum kopi." } },
        { article: "das", word: "Kind", plural: "die Kind*er*", genitive: "-es", meaning: "Anak", example: { de: "Das Kind schläft.", id: "Anak itu sedang tidur." } },
        { article: "das", word: "Baby", plural: "die Baby*s*", genitive: "-s", meaning: "Bayi", example: { de: "Das Baby weint.", id: "Bayi itu menangis." } },
        { article: "das", word: "Haus", plural: "die H*äu*s*er*", genitive: "-es", meaning: "Rumah", example: { de: "Wir kaufen ein Haus.", id: "Kami membeli sebuah rumah." } },
        { article: "die", word: "Tür", plural: "die Tür*en*", genitive: "-", meaning: "Pintu", example: { de: "Bitte mach die Tür zu.", id: "Tolong tutup pintunya." } },
        { article: "das", word: "Fenster", plural: "die Fenster", genitive: "-s", meaning: "Jendela", example: { de: "Das Fenster ist offen.", id: "Jendela itu terbuka." } },
        { article: "das", word: "Zimmer", plural: "die Zimmer", genitive: "-s", meaning: "Kamar / Ruangan", example: { de: "Mein Zimmer ist sauber.", id: "Kamarku bersih." } },
        { article: "die", word: "Küche", plural: "die Küche*n*", genitive: "-", meaning: "Dapur", example: { de: "Wir essen in der Küche.", id: "Kami makan di dapur." } },
        { article: "das", word: "Bad", plural: "die B*ä*d*er*", genitive: "-es", meaning: "Kamar Mandi", example: { de: "Das Bad ist groß.", id: "Kamar mandinya besar." } },
        { article: "die", word: "Toilette", plural: "die Toilette*n*", genitive: "-", meaning: "Toilet", example: { de: "Wo ist die Toilette?", id: "Di mana toiletnya?" } },
        { article: "die", word: "Treppe", plural: "die Treppe*n*", genitive: "-", meaning: "Tangga", example: { de: "Gehen Sie die Treppe hoch.", id: "Naiklah lewat tangga." } },
        { article: "der", word: "Keller", plural: "die Keller", genitive: "-s", meaning: "Ruang Bawah Tanah", example: { de: "Der Wein ist im Keller.", id: "Anggurnya ada di ruang bawah tanah." } },
        { article: "das", word: "Dach", plural: "die D*ä*ch*er*", genitive: "-es", meaning: "Atap", example: { de: "Das Dach ist rot.", id: "Atapnya berwarna merah." } },
        { article: "der", word: "Tisch", plural: "die Tisch*e*", genitive: "-es", meaning: "Meja", example: { de: "Das Essen steht auf dem Tisch.", id: "Makanannya ada di atas meja." } },
        { article: "der", word: "Stuhl", plural: "die St*ü*hl*e*", genitive: "-s", meaning: "Kursi", example: { de: "Der Stuhl ist bequem.", id: "Kursi itu nyaman." } },
        { article: "das", word: "Bett", plural: "die Bett*en*", genitive: "-es", meaning: "Tempat Tidur", example: { de: "Ich gehe jetzt ins Bett.", id: "Saya pergi ke tempat tidur sekarang." } },
        { article: "der", word: "Schrank", plural: "die Schr*ä*nk*e*", genitive: "-es", meaning: "Lemari", example: { de: "Die Jacke hängt im Schrank.", id: "Jaketnya tergantung di lemari." } },
        { article: "das", word: "Sofa", plural: "die Sofa*s*", genitive: "-s", meaning: "Sofa", example: { de: "Wir sitzen auf dem Sofa.", id: "Kami duduk di atas sofa." } },
        { article: "die", word: "Lampe", plural: "die Lampe*n*", genitive: "-", meaning: "Lampu", example: { de: "Mach bitte die Lampe an.", id: "Tolong nyalakan lampunya." } },
        { article: "der", word: "Fernseher", plural: "die Fernseher", genitive: "-s", meaning: "Televisi", example: { de: "Der Fernseher ist neu.", id: "Televisi itu baru." } },
        { article: "der", word: "Computer", plural: "die Computer", genitive: "-s", meaning: "Komputer", example: { de: "Ich arbeite am Computer.", id: "Saya bekerja di komputer." } },
        { article: "das", word: "Handy", plural: "die Handy*s*", genitive: "-s", meaning: "Telepon Genggam", example: { de: "Mein Handy klingelt.", id: "HP-ku berdering." } },
        { article: "das", word: "Buch", plural: "die B*ü*ch*er*", genitive: "-es", meaning: "Buku", example: { de: "Ich lese ein gutes Buch.", id: "Saya membaca buku yang bagus." } },
        { article: "der", word: "Stift", plural: "die Stift*e*", genitive: "-s", meaning: "Pena", example: { de: "Hast du einen Stift?", id: "Apakah kamu punya pena?" } },
        { article: "die", word: "Tasche", plural: "die Tasche*n*", genitive: "-", meaning: "Tas", example: { de: "Die Tasche ist schwer.", id: "Tas itu berat." } },
        { article: "der", word: "Schlüssel", plural: "die Schlüssel", genitive: "-s", meaning: "Kunci", example: { de: "Ich suche meinen Schlüssel.", id: "Saya mencari kunciku." } },
        { article: "das", word: "Geld", plural: "die Geld*er*", genitive: "-es", meaning: "Uang", example: { de: "Das kostet viel Geld.", id: "Itu harganya mahal (banyak uang)." } },
        { article: "das", word: "Bild", plural: "die Bild*er*", genitive: "-es", meaning: "Gambar", example: { de: "Das Bild häng an der Wand.", id: "Gambar itu tergantung di dinding." } },
        { article: "das", word: "Auto", plural: "die Auto*s*", genitive: "-s", meaning: "Mobil", example: { de: "Er fährt ein schnelles Auto.", id: "Dia mengendarai mobil cepat." } },
        { article: "das", word: "Fahrrad", plural: "die Fahrr*ä*d*er*", genitive: "-es", meaning: "Sepeda", example: { de: "Ich fahre mit dem Fahrrad.", id: "Saya pergi naik sepeda." } },
        { article: "der", word: "Bus", plural: "die Buss*e*", genitive: "-ses", meaning: "Bus", example: { de: "Der Bus kommt pünktlich.", id: "Bus itu datang tepat waktu." } },
        { article: "der", word: "Zug", plural: "die Z*ü*g*e*", genitive: "-es", meaning: "Kereta", example: { de: "Wir nehmen den Zug.", id: "Kami naik kereta." } },
        { article: "das", word: "Wasser", plural: "die W*ä*ss*er*", genitive: "-s", meaning: "Air", example: { de: "Kann ich bitte Wasser haben?", id: "Bolehkah saya minta air?" } },
        { article: "der", word: "Kaffee", plural: "die Kaffee*s*", genitive: "-s", meaning: "Kopi", example: { de: "Ich trinke gern Kaffee.", id: "Saya suka minum kopi." } },
        { article: "der", word: "Tee", plural: "die Tee*s*", genitive: "-s", meaning: "Teh", example: { de: "Möchtest du Tee oder Kaffee?", id: "Kamu mau teh atau kopi?" } },
        { article: "der", word: "Saft", plural: "die S*ä*ft*e*", genitive: "-es", meaning: "Jus", example: { de: "Ein Glas Apfelsaft, bitte.", id: "Tolong satu gelas jus apel." } },
        { article: "die", word: "Milch", plural: "-", genitive: "-", meaning: "Susu", example: { de: "Die Milch ist kalt.", id: "Susunya dingin." } },
        { article: "das", word: "Brot", plural: "die Brot*e*", genitive: "-es", meaning: "Roti", example: { de: "Wir kaufen frisches Brot.", id: "Kami membeli roti segar." } },
        { article: "die", word: "Butter", plural: "-", genitive: "-", meaning: "Mentega", example: { de: "Ich brauche Butter.", id: "Saya butuh mentega." } },
        { article: "der", word: "Käse", plural: "die Käse", genitive: "-s", meaning: "Keju", example: { de: "Der Käse schmeckt gut.", id: "Keju ini rasanya enak." } },
        { article: "die", word: "Wurst", plural: "die W*ü*rst*e*", genitive: "-", meaning: "Sosis", example: { de: "In Deutschland isst man viel Wurst.", id: "Di Jerman orang makan banyak sosis." } },
        { article: "das", word: "Fleisch", plural: "-", genitive: "-es", meaning: "Daging", example: { de: "Ich esse kein Fleisch.", id: "Saya tidak makan daging." } },
        { article: "der", word: "Fisch", plural: "die Fisch*e*", genitive: "-es", meaning: "Ikan", example: { de: "Der Fisch ist sehr frisch.", id: "Ikannya sangat segar." } },
        { article: "der", word: "Apfel", plural: "die *Ä*pfel", genitive: "-s", meaning: "Apel", example: { de: "Ich esse jeden Tag einen Apfel.", id: "Saya makan satu apel setiap hari." } },
        { article: "die", word: "Banane", plural: "die Banane*n*", genitive: "-", meaning: "Pisang", example: { de: "Affen mögen Bananen.", id: "Monyet menyukai pisang." } },
        { article: "die", word: "Orange", plural: "die Orange*n*", genitive: "-", meaning: "Jeruk", example: { de: "Die Orange ist süß.", id: "Jeruk ini manis." } },
        { article: "die", word: "Tomate", plural: "die Tomate*n*", genitive: "-", meaning: "Tomat", example: { de: "Wir brauchen Tomaten für den Salat.", id: "Kita butuh tomat untuk salat." } },
        { article: "die", word: "Kartoffel", plural: "die Kartoffel*n*", genitive: "-", meaning: "Kentang", example: { de: "Ich koche Kartoffeln.", id: "Saya merebus kentang." } },
        { article: "das", word: "Ei", plural: "die Ei*er*", genitive: "-s", meaning: "Telur", example: { de: "Möchtest du ein gekochtes Ei?", id: "Mau telur rebus?" } },
        { article: "das", word: "Salz", plural: "-", genitive: "-es", meaning: "Garam", example: { de: "Geben Sie mir bitte das Salz.", id: "Tolong berikan saya garamnya." } },
        { article: "der", word: "Zucker", plural: "-", genitive: "-s", meaning: "Gula", example: { de: "Ich trinke Kaffee ohne Zucker.", id: "Saya minum kopi tanpa gula." } },
        { article: "der", word: "Kuchen", plural: "die Kuchen", genitive: "-s", meaning: "Kue", example: { de: "Wer hat den Kuchen gebacken?", id: "Siapa yang membuat kue ini?" } },
        { article: "der", word: "Tag", plural: "die Tag*e*", genitive: "-es", meaning: "Hari", example: { de: "Ich wünsche dir einen schönen Tag.", id: "Semoga harimu menyenangkan." } },
        { article: "die", word: "Nacht", plural: "die N*ä*cht*e*", genitive: "-", meaning: "Malam", example: { de: "Gute Nacht!", id: "Selamat malam!" } },
        { article: "der", word: "Morgen", plural: "die Morgen", genitive: "-s", meaning: "Pagi", example: { de: "Am Morgen trinke ich Tee.", id: "Di pagi hari saya minum teh." } },
        { article: "der", word: "Abend", plural: "die Abend*e*", genitive: "-s", meaning: "Malam (Sore)", example: { de: "Was machst du heute Abend?", id: "Apa yang kamu lakukan nanti malam?" } },
        { article: "die", word: "Woche", plural: "die Woche*n*", genitive: "-", meaning: "Minggu / Pekan", example: { de: "Ich habe nächste Woche Urlaub.", id: "Saya libur minggu depan." } },
        { article: "der", word: "Monat", plural: "die Monat*e*", genitive: "-s", meaning: "Bulan", example: { de: "Ein Jahr hat zwölf Monate.", id: "Satu tahun punya 12 bulan." } },
        { article: "das", word: "Jahr", plural: "die Jahr*e*", genitive: "-es", meaning: "Tahun", example: { de: "Frohes neues Jahr!", id: "Selamat tahun baru!" } },
        { article: "die", word: "Sonne", plural: "die Sonne*n*", genitive: "-", meaning: "Matahari", example: { de: "Die Sonne scheint.", id: "Matahari bersinar." } },
        { article: "der", word: "Mond", plural: "die Mond*e*", genitive: "-es", meaning: "Bulan", example: { de: "Der Mond am Himmel ist voll.", id: "Bulan di langit sedang purnama." } },
        { article: "der", word: "Stern", plural: "die Stern*e*", genitive: "-s", meaning: "Bintang", example: { de: "Man sieht viele Sterne heute.", id: "Kita bisa melihat banyak bintang hari ini." } },
        { article: "der", word: "Baum", plural: "die B*äu*m*e*", genitive: "-es", meaning: "Pohon", example: { de: "Der Baum ist sehr hoch.", id: "Pohon itu sangat tinggi." } },
        { article: "die", word: "Blume", plural: "die Blume*n*", genitive: "-", meaning: "Bunga", example: { de: "Diese Blume riecht gut.", id: "Bunga ini harum." } },
        { article: "der", word: "Wald", plural: "die W*ä*ld*er*", genitive: "-es", meaning: "Hutan", example: { de: "Wir spazieren im Wald.", id: "Kami berjalan-jalan di hutan." } },
        { article: "der", word: "Berg", plural: "die Berg*e*", genitive: "-es", meaning: "Gunung", example: { de: "Er wandert gern im Berg.", id: "Dia suka mendaki di gunung." } },
        { article: "der", word: "Fluss", plural: "die Fl*ü*ss*e*", genitive: "-es", meaning: "Sungai", example: { de: "Der Fluss ist tief.", id: "Sungai itu dalam." } },
        { article: "das", word: "Meer", plural: "die Meer*e*", genitive: "-es", meaning: "Laut", example: { de: "Im Sommer fahren wir ans Meer.", id: "Di musim panas kami pergi ke laut." } },
        { article: "der", word: "Himmel", plural: "die Himmel", genitive: "-s", meaning: "Langit", example: { de: "Der Himmel ist blau.", id: "Langit berwarna biru." } },
        { article: "der", word: "Kopf", plural: "die K*ö*pf*e*", genitive: "-es", meaning: "Kepala", example: { de: "Mein Kopf tut weh.", id: "Kepalaku sakit." } },
        { article: "das", word: "Auge", plural: "die Auge*n*", genitive: "-s", meaning: "Mata", example: { de: "Sie hat blaue Augen.", id: "Dia bermata biru." } },
        { article: "das", word: "Ohr", plural: "die Ohr*en*", genitive: "-es", meaning: "Telinga", example: { de: "Der Elefant hat große Ohren.", id: "Gajah punya telinga yang besar." } },
        { article: "die", word: "Nase", plural: "die Nase*n*", genitive: "-", meaning: "Hidung", example: { de: "Der Hund hat eine kalte Nase.", id: "Anjing itu berhidung dingin." } },
        { article: "der", word: "Mund", plural: "die M*ü*nd*er*", genitive: "-es", meaning: "Mulut", example: { de: "Bitte mach den Mund auf.", id: "Tolong buka mulutmu." } },
        { article: "der", word: "Arm", plural: "die Arm*e*", genitive: "-es", meaning: "Lengan", example: { de: "Er hat sich den Arm gebrochen.", id: "Dia mematahkan lengannya." } },
        { article: "die", word: "Hand", plural: "die H*ä*nd*e*", genitive: "-", meaning: "Tangan", example: { de: "Wasche dir bitte die Hände.", id: "Tolong cuci tanganmu." } },
        { article: "das", word: "Bein", plural: "die Bein*e*", genitive: "-es", meaning: "Kaki (Tungkai)", example: { de: "Mein Bein tut weh.", id: "Kakiku sakit." } },
        { article: "der", word: "Fuß", plural: "die F*ü*ß*e*", genitive: "-es", meaning: "Telapak Kaki", example: { de: "Ich gehe zu Fuß.", id: "Saya jalan kaki." } },
        { article: "der", word: "Hund", plural: "die Hund*e*", genitive: "-es", meaning: "Anjing", example: { de: "Der Hund bellt laut.", id: "Anjing itu menggonggong keras." } },
        { article: "die", word: "Katze", plural: "die Katze*n*", genitive: "-", meaning: "Kucing", example: { de: "Ich habe eine Katze.", id: "Saya punya seekor kucing." } },
        { article: "der", word: "Vogel", plural: "die V*ö*gel", genitive: "-s", meaning: "Burung", example: { de: "Der Vogel singt im Baum.", id: "Burung itu bernyanyi di pohon." } },
        { article: "die", word: "Maus", plural: "die M*äu*s*e*", genitive: "-", meaning: "Tikus", example: { de: "Die Katze fängt eine Maus.", id: "Kucing menangkap tikus." } },
        { article: "das", word: "Pferd", plural: "die Pferd*e*", genitive: "-es", meaning: "Kuda", example: { de: "Das Mädchen reitet auf dem Pferd.", id: "Anak perempuan itu menunggang kuda." } },
        { article: "die", word: "Kuh", plural: "die K*ü*h*e*", genitive: "-", meaning: "Sapi", example: { de: "Die Kuh gibt Milch.", id: "Sapi menghasilkan susu." } },
        { article: "das", word: "Schwein", plural: "die Schwein*e*", genitive: "-s", meaning: "Babi", example: { de: "Das Schwein ist rosa.", id: "Babi itu berwarna merah muda." } },
        { article: "die", word: "Stadt", plural: "die St*ä*dt*e*", genitive: "-", meaning: "Kota", example: { de: "Jakarta ist eine große Stadt.", id: "Jakarta adalah kota yang besar." } },
        { article: "das", word: "Dorf", plural: "die D*ö*rf*er*", genitive: "-es", meaning: "Desa", example: { de: "Meine Großeltern wohnen in einem Dorf.", id: "Kakek nenekku tinggal di desa." } },
        { article: "die", word: "Straße", plural: "die Straße*n*", genitive: "-", meaning: "Jalan", example: { de: "In welcher Straße wohnst du?", id: "Kamu tinggal di jalan apa?" } },
        { article: "der", word: "Platz", plural: "die Pl*ä*tz*e*", genitive: "-es", meaning: "Tempat / Alun-alun", example: { de: "Ist dieser Platz noch frei?", id: "Apakah tempat/kursi ini masih kosong?" } },
        { article: "der", word: "Park", plural: "die Park*s*", genitive: "-s", meaning: "Taman", example: { de: "Wir joggen im Park.", id: "Kami joging di taman." } },
        { article: "die", word: "Schule", plural: "die Schule*n*", genitive: "-", meaning: "Sekolah", example: { de: "Die Kinder gehen zur Schule.", id: "Anak-anak pergi ke sekolah." } },
        { article: "die", word: "Universität", plural: "die Universität*en*", genitive: "-", meaning: "Universitas", example: { de: "Er studiert an der Universität.", id: "Dia kuliah di universitas." } },
        { article: "das", word: "Restaurant", plural: "die Restaurant*s*", genitive: "-s", meaning: "Restoran", example: { de: "Wir essen heute im Restaurant.", id: "Hari ini kita makan di restoran." } },
        { article: "das", word: "Café", plural: "die Café*s*", genitive: "-s", meaning: "Kafe", example: { de: "Treffen wir uns im Café?", id: "Ketemu di kafe yuk?" } },
        { article: "der", word: "Supermarkt", plural: "die Superm*ä*rkt*e*", genitive: "-es", meaning: "Supermarket", example: { de: "Der Supermarkt schließt um 20 Uhr.", id: "Supermarket tutup jam 8 malam." } },
        { article: "der", word: "Markt", plural: "die M*ä*rkt*e*", genitive: "-es", meaning: "Pasar", example: { de: "Ich kaufe Obst auf dem Markt.", id: "Saya membeli buah di pasar." } },
        { article: "der", word: "Bahnhof", plural: "die Bahnh*ö*f*e*", genitive: "-es", meaning: "Stasiun", example: { de: "Der Zug steht am Bahnhof.", id: "Kereta ada di stasiun." } },
        { article: "der", word: "Flughafen", plural: "die Flugh*ä*f*en*", genitive: "-s", meaning: "Bandara", example: { de: "Wir fahren zum Flughafen.", id: "Kami pergi ke bandara." } },
        { article: "die", word: "Hose", plural: "die Hose*n*", genitive: "-", meaning: "Celana", example: { de: "Die schwarze Hose gefällt mir.", id: "Saya suka celana hitam itu." } },
        { article: "das", word: "Hemd", plural: "die Hemd*en*", genitive: "-es", meaning: "Kemeja", example: { de: "Er trägt ein weißes Hemd.", id: "Dia memakai kemeja putih." } },
        { article: "das", word: "T-Shirt", plural: "die T-Shirt*s*", genitive: "-s", meaning: "Kaos", example: { de: "Das T-Shirt ist zu groß.", id: "Kaos ini kebesaran." } },
        { article: "der", word: "Pullover", plural: "die Pullover", genitive: "-s", meaning: "Baju Hangat", example: { de: "Im Winter brauche ich einen Pullover.", id: "Di musim dingin saya butuh sweater." } },
        { article: "die", word: "Jacke", plural: "die Jacke*n*", genitive: "-", meaning: "Jaket", example: { de: "Vergiss deine Jacke nicht!", id: "Jangan lupa jaketmu!" } },
        { article: "der", word: "Mantel", plural: "die M*ä*ntel", genitive: "-s", meaning: "Mantel", example: { de: "Der Mantel hält sehr warm.", id: "Mantel ini sangat menghangatkan." } },
        { article: "der", word: "Schuh", plural: "die Schuh*e*", genitive: "-es", meaning: "Sepatu", example: { de: "Zieh bitte deine Schuhe aus.", id: "Tolong lepas sepatumu." } },
        { article: "die", word: "Socke", plural: "die Socke*n*", genitive: "-", meaning: "Kaos Kaki", example: { de: "Wo sind meine Socken?", id: "Di mana kaos kakiku?" } },
        { article: "der", word: "Hut", plural: "die H*ü*t*e*", genitive: "-es", meaning: "Topi", example: { de: "Er trägt einen eleganten Hut.", id: "Dia memakai topi yang elegan." } },
        { article: "die", word: "Brille", plural: "die Brille*n*", genitive: "-", meaning: "Kacamata", example: { de: "Ich brauche eine neue Brille.", id: "Saya butuh kacamata baru." } },
        { article: "der", word: "Name", plural: "die Name*n*", genitive: "-ns", meaning: "Nama", example: { de: "Wie ist Ihr Name?", id: "Siapa nama Anda?" } },
        { article: "die", word: "Zahl", plural: "die Zahl*en*", genitive: "-", meaning: "Angka", example: { de: "Schreiben Sie die Zahl auf.", id: "Tuliskan angkanya." } },
        { article: "die", word: "Farbe", plural: "die Farbe*n*", genitive: "-", meaning: "Warna", example: { de: "Blau ist meine Lieblingsfarbe.", id: "Biru adalah warna favoritku." } },
        { article: "die", word: "Frage", plural: "die Frage*n*", genitive: "-", meaning: "Pertanyaan", example: { de: "Ich habe eine Frage.", id: "Saya punya satu pertanyaan." } },
        { article: "die", word: "Antwort", plural: "die Antwort*en*", genitive: "-", meaning: "Antwort / Jawaban", example: { de: "Das ist die richtige Antwort.", id: "Itu jawaban yang benar." } },
        { article: "der", word: "Fehler", plural: "die Fehler", genitive: "-s", meaning: "Kesalahan", example: { de: "Niemand ist ohne Fehler.", id: "Tak ada orang tanpa kesalahan." } },
        { article: "das", word: "Problem", plural: "die Problem*e*", genitive: "-s", meaning: "Masalah", example: { de: "Kein Problem!", id: "Tidak masalah!" } },
        { article: "das", word: "Beispiel", plural: "die Beispiel*e*", genitive: "-s", meaning: "Contoh", example: { de: "Kannst du mir ein Beispiel geben?", id: "Bisa berikan saya contoh?" } },
        { article: "das", word: "Wort", plural: "die W*ö*rt*er*", genitive: "-es", meaning: "Kata", example: { de: "Was bedeutet dieses Wort?", id: "Apa arti kata ini?" } },
        { article: "der", word: "Satz", plural: "die S*ä*tz*e*", genitive: "-es", meaning: "Kalimat", example: { de: "Schreiben Sie bitte einen Satz.", id: "Tolong tulis satu kalimat." } },
        { article: "die", word: "Sprache", plural: "die Sprache*n*", genitive: "-", meaning: "Bahasa", example: { de: "Welche Sprachen sprichst du?", id: "Bahasa apa saja yang kamu kuasai?" } },
        { article: "der", word: "Text", plural: "die Text*e*", genitive: "-es", meaning: "Teks", example: { de: "Lesen Sie den Text auf Seite 5.", id: "Bacalah teks di halaman 5." } },
        { article: "der", word: "Brief", plural: "die Brief*e*", genitive: "-es", meaning: "Surat", example: { de: "Ich schreibe einen Brief.", id: "Saya menulis sepucuk surat." } },
        { article: "die", word: "E-Mail", plural: "die E-Mail*s*", genitive: "-", meaning: "Email", example: { de: "Ich schicke dir eine E-Mail.", id: "Saya kirimkan kamu email." } },
        { article: "das", word: "Spiel", plural: "die Spiel*e*", genitive: "-s", meaning: "Permainan", example: { de: "Das Spiel macht Spaß.", id: "Permainannya seru." } },
        { article: "der", word: "Freund", plural: "die Freund*e*", genitive: "-es", meaning: "Teman (Pria)", example: { de: "Er ist mein bester Freund.", id: "Dia adalah sahabat baikku." } },
        { article: "die", word: "Freundin", plural: "die Freundin*nen*", genitive: "-", meaning: "Teman (Wanita)", example: { de: "Das ist meine Freundin Anna.", id: "Ini temanku, Anna." } },
        { article: "der", word: "Beruf", plural: "die Beruf*e*", genitive: "-es", meaning: "Pekerjaan", example: { de: "Was sind Sie von Beruf?", id: "Apa pekerjaan Anda?" } },
        { article: "die", word: "Arbeit", plural: "die Arbeit*en*", genitive: "-", meaning: "Kerja", example: { de: "Ich fahre jetzt zur Arbeit.", id: "Saya berangkat kerja sekarang." } }
    ],
    "A2": [
        { article: "das", word: "Büro", plural: "die Büro*s*", genitive: "-s", meaning: "Kantor", example: { de: "Ich bin noch im Büro.", id: "Saya masih di kantor." } },
        { article: "der", word: "Chef", plural: "die Chef*s*", genitive: "-s", meaning: "Bos", example: { de: "Der Chef ist heute in einer Besprechung.", id: "Bos sedang rapat hari ini." } },
        { article: "der", word: "Kollege", plural: "die Kollege*n*", genitive: "-n", meaning: "Rekan Kerja", example: { de: "Meine Kollegen sind sehr nett.", id: "Rekan-rekan kerjaku sangat ramah." } },
        { article: "der", word: "Mitarbeiter", plural: "die Mitarbeiter", genitive: "-s", meaning: "Karyawan", example: { de: "Die Firma hat 100 Mitarbeiter.", id: "Perusahaan itu punya 100 karyawan." } },
        { article: "der", word: "Lehrer", plural: "die Lehrer", genitive: "-s", meaning: "Guru", example: { de: "Der Lehrer erklärt die Grammatik.", id: "Guru menjelaskan tata bahasa." } },
        { article: "der", word: "Schüler", plural: "die Schüler", genitive: "-s", meaning: "Siswa", example: { de: "Die Schüler machen ihre Hausaufgaben.", id: "Para siswa mengerjakan PR mereka." } },
        { article: "der", word: "Student", plural: "die Student*en*", genitive: "-en", meaning: "Mahasiswa", example: { de: "Die Studenten lernen in der Bibliothek.", id: "Para mahasiswa belajar di perpustakaan." } },
        { article: "der", word: "Bäcker", plural: "die Bäcker", genitive: "-s", meaning: "Pembuat Roti", example: { de: "Der Bäcker backt frisches Brot.", id: "Tukang roti memanggang roti segar." } },
        { article: "der", word: "Kellner", plural: "die Kellner", genitive: "-s", meaning: "Pelayan", example: { de: "Der Kellner bringt die Speisekarte.", id: "Pelayan membawakan buku menu." } },
        { article: "der", word: "Verkäufer", plural: "die Verkäufer", genitive: "-s", meaning: "Penjual", example: { de: "Der Verkäufer hilft dem Kunden.", id: "Penjual membantu pelanggan." } },
        { article: "die", word: "Firma", plural: "die Firm*en*", genitive: "-", meaning: "Perusahaan", example: { de: "Er arbeitet bei einer großen Firma.", id: "Dia bekerja di sebuah perusahaan besar." } },
        { article: "der", word: "Termin", plural: "die Termin*e*", genitive: "-s", meaning: "Janji Temu", example: { de: "Ich habe morgen einen Termin beim Arzt.", id: "Besok saya ada janji dengan dokter." } },
        { article: "die", word: "Besprechung", plural: "die Besprechung*en*", genitive: "-", meaning: "Rapat", example: { de: "Die Besprechung beginnt um 10 Uhr.", id: "Rapat dimulai jam 10 pagi." } },
        { article: "der", word: "Vertrag", plural: "die Vertr*ä*g*e*", genitive: "-es", meaning: "Kontrak", example: { de: "Ich habe den Arbeitsvertrag unterschrieben.", id: "Saya sudah menandatangani kontrak kerja." } },
        { article: "das", word: "Praktikum", plural: "die Praktik*a*", genitive: "-s", meaning: "Magang", example: { de: "Ich mache ein Praktikum als Videoeditor.", id: "Saya magang sebagai editor video." } },
        { article: "die", word: "Erfahrung", plural: "die Erfahrung*en*", genitive: "-", meaning: "Pengalaman", example: { de: "Er hat viel Erfahrung in diesem Beruf.", id: "Dia punya banyak pengalaman di pekerjaan ini." } },
        { article: "die", word: "Pause", plural: "die Pause*n*", genitive: "-", meaning: "Istirahat", example: { de: "Machen wir 15 Minuten Pause!", id: "Ayo kita istirahat 15 menit!" } },
        { article: "der", word: "Feierabend", plural: "die Feierabend*e*", genitive: "-s", meaning: "Selesai Kerja", example: { de: "Wann hast du heute Feierabend?", id: "Kapan kamu selesai kerja hari ini?" } },
        { article: "die", word: "Reise", plural: "die Reise*n*", genitive: "-", meaning: "Perjalanan", example: { de: "Ich wünsche dir eine gute Reise!", id: "Semoga perjalananmu menyenangkan!" } },
        { article: "der", word: "Urlaub", plural: "die Urlaub*e*", genitive: "-s", meaning: "Liburan", example: { de: "Ich fahre im Urlaub nach Indonesien.", id: "Saya pergi ke Indonesia saat liburan." } },
        { article: "der", word: "Koffer", plural: "die Koffer", genitive: "-s", meaning: "Koper", example: { de: "Mein Koffer ist schon gepackt.", id: "Koperku sudah dikemas." } },
        { article: "das", word: "Gepäck", plural: "die Gepäck*stücke*", genitive: "-es", meaning: "Bagasi", example: { de: "Wo kann ich mein Gepäck abholen?", id: "Di mana saya bisa mengambil bagasiku?" } },
        { article: "die", word: "Fahrkarte", plural: "die Fahrkarte*n*", genitive: "-", meaning: "Tiket Perjalanan", example: { de: "Bitte zeigen Sie Ihre Fahrkarte.", id: "Tolong tunjukkan tiket perjalanan Anda." } },
        { article: "das", word: "Ticket", plural: "die Ticket*s*", genitive: "-s", meaning: "Tiket", example: { de: "Ich buche das Ticket online.", id: "Saya memesan tiket secara online." } },
        { article: "der", word: "Flug", plural: "die Fl*ü*g*e*", genitive: "-es", meaning: "Penerbangan", example: { de: "Der Flug nach Frankfurt dauert 14 Stunden.", id: "Penerbangan ke Frankfurt memakan waktu 14 jam." } },
        { article: "das", word: "Flugzeug", plural: "die Flugzeug*e*", genitive: "-es", meaning: "Pesawat Terbang", example: { de: "Das Flugzeug startet gleich.", id: "Pesawat terbangnya akan segera lepas landas." } },
        { article: "der", word: "Hubschrauber", plural: "die Hubschrauber", genitive: "-s", meaning: "Helikopter", example: { de: "Ein Hubschrauber fliegt über die Stadt.", id: "Seperangkat helikopter terbang di atas kota." } },
        { article: "die", word: "U-Bahn", plural: "die U-Bahn*en*", genitive: "-", meaning: "Kereta Bawah Tanah", example: { de: "Wir nehmen die U-Bahn ins Zentrum.", id: "Kita naik kereta bawah tanah ke pusat kota." } },
        { article: "die", word: "Straßenbahn", plural: "die Straßenbahn*en*", genitive: "-", meaning: "Trem", example: { de: "Die Straßenbahn fährt jede 10 Minuten.", id: "Trem beroperasi setiap 10 menit." } },
        { article: "das", word: "Schiff", plural: "die Schiff*e*", genitive: "-es", meaning: "Kapal", example: { de: "Das Schiff fährt auf dem Rhein.", id: "Kapal itu berlayar di sungai Rhein." } },
        { article: "das", word: "Boot", plural: "die Boot*e*", genitive: "-es", meaning: "Perahu", example: { de: "Wir mieten ein kleines Boot.", id: "Kami menyewa sebuah perahu kecil." } },
        { article: "der", word: "Motorroller", plural: "die Motorroller", genitive: "-s", meaning: "Skuter Motor", example: { de: "Er fährt mit dem Motorroller zur Arbeit.", id: "Dia naik skuter motor ke tempat kerja." } },
        { article: "der", word: "Verkehr", plural: "-", genitive: "-s", meaning: "Lalu Lintas", example: { de: "Heute gibt es viel Verkehr.", id: "Hari ini lalu lintas sangat padat." } },
        { article: "die", word: "Ampel", plural: "die Ampel*n*", genitive: "-", meaning: "Lampu Lalu Lintas", example: { de: "Die Ampel ist rot, du musst warten.", id: "Lampu merah, kamu harus menunggu." } },
        { article: "die", word: "Kreuzung", plural: "die Kreuzung*en*", genitive: "-", meaning: "Persimpangan", example: { de: "An der Kreuzung biegen Sie links ab.", id: "Di persimpangan, Anda belok kiri." } },
        { article: "der", word: "Weg", plural: "die Weg*e*", genitive: "-es", meaning: "Jalan / Rute", example: { de: "Können Sie mir den Weg zeigen?", id: "Bisa tunjukkan saya jalannya?" } },
        { article: "die", word: "Richtung", plural: "die Richtung*en*", genitive: "-", meaning: "Arah", example: { de: "Wählen Sie die richtige Richtung.", id: "Pilihlah arah yang benar." } },
        { article: "die", word: "Grenze", plural: "die Grenze*n*", genitive: "-", meaning: "Perbatasan", example: { de: "Wir zeigen den Pass an der Grenze.", id: "Kami menunjukkan paspor di perbatasan." } },
        { article: "das", word: "Hotel", plural: "die Hotel*s*", genitive: "-s", meaning: "Hotel", example: { de: "Das Hotel hat fünf Sterne.", id: "Hotel itu bintang lima." } },
        { article: "die", word: "Pension", plural: "die Pension*en*", genitive: "-", meaning: "Penginapan", example: { de: "Wir übernachten in einer günstigen Pension.", id: "Kami menginap di penginapan yang murah." } },
        { article: "das", word: "Zelt", plural: "die Zelt*e*", genitive: "-es", meaning: "Tenda", example: { de: "Wir schlafen im Zelt am Strand.", id: "Kami tidur di dalam tenda di pantai." } },
        { article: "der", word: "Tourist", plural: "die Tourist*en*", genitive: "-en", meaning: "Turis", example: { de: "Viele Touristen besuchen Bali.", id: "Banyak turis mengunjungi Bali." } },
        { article: "der", word: "Ausflug", plural: "die Ausfl*ü*g*e*", genitive: "-es", meaning: "Tamasya", example: { de: "Am Wochenende machen wir einen Ausflug.", id: "Akhir pekan ini kami akan tamasya." } },
        { article: "die", word: "Sehenswürdigkeit", plural: "die Sehenswürdigkeit*en*", genitive: "-", meaning: "Objek Wisata", example: { de: "Welche Sehenswürdigkeiten gibt es hier?", id: "Objek wisata apa saja yang ada di sini?" } },
        { article: "das", word: "Gebäude", plural: "die Gebäude", genitive: "-s", meaning: "Bangunan", example: { de: "Das ist ein sehr altes Gebäude.", id: "Itu adalah bangunan yang sangat tua." } },
        { article: "das", word: "Zentrum", plural: "die Zentr*en*", genitive: "-s", meaning: "Pusat Kota", example: { de: "Wir treffen uns im Zentrum.", id: "Kita bertemu di pusat kota." } },
        { article: "die", word: "Brücke", plural: "die Brücke*n*", genitive: "-", meaning: "Jembatan", example: { de: "Die Brücke ist 100 Meter lang.", id: "Jembatan itu panjangnya 100 meter." } },
        { article: "der", word: "Turm", plural: "die T*ü*rm*e*", genitive: "-es", meaning: "Menara", example: { de: "Man kann auf den Turm steigen.", id: "Orang bisa naik ke atas menara itu." } },
        { article: "das", word: "Rathaus", plural: "die Rath*äu*s*er*", genitive: "-es", meaning: "Balai Kota", example: { de: "Das Rathaus steht am Marktplatz.", id: "Balai kota terletak di alun-alun pasar." } },
        { article: "die", word: "Polizei", plural: "-", genitive: "-", meaning: "Polisi", example: { de: "Rufen Sie bitte die Polizei!", id: "Tolong panggil polisi!" } },
        { article: "die", word: "Feuerwehr", plural: "die Feuerwehr*en*", genitive: "-", meaning: "Pemadam", example: { de: "Die Feuerwehr war schnell da.", id: "Pemadam kebakaran datang dengan cepat." } },
        { article: "die", word: "Post", plural: "-", genitive: "-", meaning: "Kantor Pos", example: { de: "Ich bringe das Paket zur Post.", id: "Saya membawa paket itu ke kantor pos." } },
        { article: "die", word: "Bank", plural: "die Bank*en*", genitive: "-", meaning: "Bank", example: { de: "Die Bank öffnet um 9 Uhr.", id: "Bank buka jam 9 pagi." } },
        { article: "das", word: "Konto", plural: "die Kont*en*", genitive: "-s", meaning: "Rekening", example: { de: "Ich möchte ein Konto eröffnen.", id: "Saya ingin membuka rekening." } },
        { article: "der", word: "Automat", plural: "die Automat*en*", genitive: "-en", meaning: "Mesin Otomatis", example: { de: "Der Ticketautomat ist kaputt.", id: "Mesin tiket otomatisnya rusak." } },
        { article: "die", word: "Apotheke", plural: "die Apotheke*n*", genitive: "-", meaning: "Apotek", example: { de: "Ich kaufe Medikamente in der Apotheke.", id: "Saya membeli obat di apotek." } },
        { article: "das", word: "Krankenhaus", plural: "die Krankenh*äu*s*er*", genitive: "-es", meaning: "Rumah Sakit", example: { de: "Er liegt im Krankenhaus.", id: "Dia dirawat di rumah sakit." } },
        { article: "die", word: "Kirche", plural: "die Kirche*n*", genitive: "-", meaning: "Gereja", example: { de: "Am Sonntag geht sie in die Kirche.", id: "Hari Minggu dia pergi ke gereja." } },
        { article: "das", word: "Museum", plural: "die Muse*en*", genitive: "-s", meaning: "Museum", example: { de: "Das Museum ist montags geschlossen.", id: "Museum tutup setiap hari Senin." } },
        { article: "das", word: "Theater", plural: "die Theater", genitive: "-s", meaning: "Teater", example: { de: "Wir haben Karten für das Theater.", id: "Kami punya tiket untuk teater." } },
        { article: "das", word: "Kino", plural: "die Kino*s*", genitive: "-s", meaning: "Bioskop", example: { de: "Gehen wir heute Abend ins Kino?", id: "Nanti malam kita ke bioskop yuk?" } },
        { article: "die", word: "Bibliothek", plural: "die Bibliothek*en*", genitive: "-", meaning: "Perpustakaan", example: { de: "Ich leihe Bücher in der Bibliothek aus.", id: "Saya meminjam buku di perpustakaan." } },
        { article: "der", word: "Einwohner", plural: "die Einwohner", genitive: "-s", meaning: "Penduduk", example: { de: "Palembang hat über 1,6 Millionen Einwohner.", id: "Palembang punya lebih dari 1,6 juta penduduk." } },
        { article: "die", word: "Gesellschaft", plural: "die Gesellschaft*en*", genitive: "-", meaning: "Masyarakat", example: { de: "Wir leben in einer modernen Gesellschaft.", id: "Kita hidup di masyarakat modern." } },
        { article: "der", word: "Staat", plural: "die Staat*en*", genitive: "-es", meaning: "Negara (Sistem)", example: { de: "Der Staat hilft den Bürgern.", id: "Negara membantu warga." } },
        { article: "das", word: "Land", plural: "die L*ä*nd*er*", genitive: "-es", meaning: "Negara", example: { de: "Deutschland ist ein schönes Land.", id: "Jerman adalah negara yang indah." } },
        { article: "die", word: "Welt", plural: "die Welt*en*", genitive: "-", meaning: "Dunia", example: { de: "Er reist um die ganze Welt.", id: "Dia keliling dunia." } },
        { article: "der", word: "Einkauf", plural: "die Eink*äu*f*e*", genitive: "-s", meaning: "Belanjaan", example: { de: "Ich bezahle für meinen Einkauf.", id: "Saya membayar belanjaan saya." } },
        { article: "das", word: "Angebot", plural: "die Angebot*e*", genitive: "-s", meaning: "Penawaran", example: { de: "Das ist ein sehr gutes Angebot.", id: "Itu adalah penawaran yang sangat bagus." } },
        { article: "der", word: "Preis", plural: "die Preis*e*", genitive: "-es", meaning: "Harga", example: { de: "Der Preis ist etwas hoch.", id: "Harganya sedikit mahal." } },
        { article: "die", word: "Kasse", plural: "die Kasse*n*", genitive: "-", meaning: "Kasir", example: { de: "Zahlen Sie bitte an der Kasse.", id: "Tolong bayar di kasir." } },
        { article: "die", word: "Quittung", plural: "die Quittung*en*", genitive: "-", meaning: "Quittung / Kuitansi", example: { de: "Brauchen Sie eine Quittung?", id: "Apakah Anda butuh struk/kuitansi?" } },
        { article: "die", word: "Größe", plural: "die Größe*n*", genitive: "-", meaning: "Ukuran", example: { de: "Haben Sie das in Größe M?", id: "Apakah ada ukuran M?" } },
        { article: "das", word: "Kleid", plural: "die Kleid*er*", genitive: "-es", meaning: "Gaun", example: { de: "Das blaue Kleid steht dir gut.", id: "Gaun biru itu cocok untukmu." } },
        { article: "der", word: "Rock", plural: "die R*ö*ck*e*", genitive: "-es", meaning: "Rok", example: { de: "Sie kauft einen neuen Rock.", id: "Dia membeli rok baru." } },
        { article: "der", word: "Anzug", plural: "die Anz*ü*g*e*", genitive: "-es", meaning: "Setelan Jas", example: { de: "Er trägt einen schwarzen Anzug.", id: "Dia mengenakan setelan jas hitam." } },
        { article: "die", word: "Krawatte", plural: "die Krawatte*n*", genitive: "-", meaning: "Dasi", example: { de: "Die Krawatte passt gut zum Hemd.", id: "Dasinya cocok dengan kemejanya." } },
        { article: "der", word: "Gürtel", plural: "die Gürtel", genitive: "-s", meaning: "Sabuk", example: { de: "Mein Gürtel ist aus Leder.", id: "Sabukku terbuat dari kulit." } },
        { article: "der", word: "Handschuh", plural: "die Handschuh*e*", genitive: "-s", meaning: "Sarung Tangan", example: { de: "Mir ist kalt, ich brauche Handschuhe.", id: "Saya kedinginan, saya butuh sarung tangan." } },
        { article: "der", word: "Schal", plural: "die Schal*s*", genitive: "-s", meaning: "Syal", example: { de: "Sie schenkt ihm einen Schal.", id: "Dia menghadiahkannya sebuah syal." } },
        { article: "der", word: "Schmuck", plural: "die Schmuck*e*", genitive: "-es", meaning: "Perhiasan", example: { de: "Sie trägt gern goldenen Schmuck.", id: "Dia suka memakai perhiasan emas." } },
        { article: "die", word: "Uhr", plural: "die Uhr*en*", genitive: "-", meaning: "Jam", example: { de: "Wie viel Uhr ist es?", id: "Jam berapa sekarang?" } },
        { article: "der", word: "Regenschirm", plural: "die Regenschirm*e*", genitive: "-s", meaning: "Payung", example: { de: "Es regnet, nimm den Regenschirm mit!", id: "Hujan, bawalah payung itu!" } },
        { article: "das", word: "Wetter", plural: "-", genitive: "-s", meaning: "Cuaca", example: { de: "Das Wetter heute ist wunderschön.", id: "Cuaca hari ini sangat indah." } },
        { article: "der", word: "Regen", plural: "die Regen", genitive: "-s", meaning: "Hujan", example: { de: "Ich mag den Regen nicht.", id: "Saya tidak suka hujan." } },
        { article: "der", word: "Schnee", plural: "-", genitive: "-s", meaning: "Salju", example: { de: "Im Winter fällt viel Schnee.", id: "Di musim dingin turun banyak salju." } },
        { article: "der", word: "Wind", plural: "die Wind*e*", genitive: "-es", meaning: "Angin", example: { de: "Der Wind weht heute sehr stark.", id: "Angin bertiup sangat kencang hari ini." } },
        { article: "der", word: "Sturm", plural: "die St*ü*rm*e*", genitive: "-es", meaning: "Badai", example: { de: "Der Sturm hat einen Baum umgeworfen.", id: "Badai telah menumbangkan sebatang pohon." } },
        { article: "die", word: "Wolke", plural: "die Wolke*n*", genitive: "-", meaning: "Awan", example: { de: "Es gibt keine Wolken am Himmel.", id: "Tidak ada awan di langit." } },
        { article: "das", word: "Gewitter", plural: "die Gewitter", genitive: "-s", meaning: "Badai Petir", example: { de: "Ich habe Angst vor Gewitter.", id: "Saya takut dengan badai petir." } },
        { article: "der", word: "Frühling", plural: "die Frühling*e*", genitive: "-s", meaning: "Musim Semi", example: { de: "Im Frühling blühen die Blumen.", id: "Di musim semi bunga-bunga bermekaran." } },
        { article: "der", word: "Sommer", plural: "die Sommer", genitive: "-s", meaning: "Musim Panas", example: { de: "Im Sommer ist es hier sehr heiß.", id: "Di musim panas di sini sangat panas." } },
        { article: "der", word: "Herbst", plural: "die Herbst*e*", genitive: "-es", meaning: "Musim Gugur", example: { de: "Im Herbst fallen die Blätter.", id: "Di musim gugur daun-daun berjatuhan." } },
        { article: "der", word: "Winter", plural: "die Winter", genitive: "-s", meaning: "Musim Dingin", example: { de: "Im Winter gehen wir Ski fahren.", id: "Di musim dingin kami pergi bermain ski." } },
        { article: "die", word: "Pflanze", plural: "die Pflanze*n*", genitive: "-", meaning: "Tanaman", example: { de: "Diese Pflanze braucht viel Wasser.", id: "Tanaman ini butuh banyak air." } },
        { article: "das", word: "Tier", plural: "die Tier*e*", genitive: "-es", meaning: "Hewan", example: { de: "Der Hund ist ein treues Tier.", id: "Anjing adalah hewan yang setia." } },
        { article: "der", word: "Strand", plural: "die Str*ä*nd*e*", genitive: "-es", meaning: "Pantai", example: { de: "Wir liegen den ganzen Tag am Strand.", id: "Kami berbaring seharian di pantai." } },
        { article: "die", word: "Insel", plural: "die Insel*n*", genitive: "-", meaning: "Pulau", example: { de: "Bali ist eine wunderschöne Insel.", id: "Bali adalah pulau yang sangat indah." } },
        { article: "der", word: "See", plural: "die See*n*", genitive: "-s", meaning: "Danau", example: { de: "Der See ist im Winter gefroren.", id: "Danau itu membeku di musim dingin." } },
        { article: "das", word: "Tal", plural: "die T*ä*l*er*", genitive: "-es", meaning: "Lembah", example: { de: "Das Dorf liegt in einem tiefen Tal.", id: "Desa itu terletak di lembah yang dalam." } },
        { article: "der", word: "Hügel", plural: "die Hügel", genitive: "-s", meaning: "Bukit", example: { de: "Wir steigen auf den Hügel.", id: "Kita mendaki ke atas bukit." } },
        { article: "das", word: "Hobby", plural: "die Hobby*s*", genitive: "-s", meaning: "Hobi", example: { de: "Was sind deine Hobbys?", id: "Apa saja hobimu?" } },
        { article: "der", word: "Sport", plural: "die Sport*arten*", genitive: "-s", meaning: "Olahraga", example: { de: "Treibst du gern Sport?", id: "Apakah kamu suka berolahraga?" } },
        { article: "der", word: "Ball", plural: "die B*ä*ll*e*", genitive: "-es", meaning: "Bola", example: { de: "Der Junge wirft den Ball.", id: "Anak laki-laki itu melempar bola." } },
        { article: "das", word: "Stadion", plural: "die Radi*en*", genitive: "-s", meaning: "Stadion", example: { de: "Das Stadion ist voll.", id: "Stadionnya penuh." } },
        { article: "der", word: "Verein", plural: "die Verein*e*", genitive: "-s", meaning: "Klub", example: { de: "Ich bin Mitglied im Fußballverein.", id: "Saya anggota klub sepak bola." } },
        { article: "die", word: "Musik", plural: "-", genitive: "-", meaning: "Musik", example: { de: "Ich höre beim Arbeiten gern Musik.", id: "Saya suka dengerin musik saat bekerja." } },
        { article: "das", word: "Lied", plural: "die Lied*er*", genitive: "-es", meaning: "Lagu", example: { de: "Dieses Lied gefällt mir sehr gut.", id: "Saya sangat menyukai lagu ini." } },
        { article: "das", word: "Konzert", plural: "die Konzert*e*", genitive: "-s", meaning: "Konser", example: { de: "Das Konzert beginnt gleich.", id: "Konsernya akan segera dimulai." } },
        { article: "das", word: "Instrument", plural: "die Instrument*e*", genitive: "-s", meaning: "Instrumen", example: { de: "Spielst du ein Instrument?", id: "Apakah kamu bisa main alat musik?" } },
        { article: "die", word: "Kunst", plural: "die K*ü*nst*e*", genitive: "-", meaning: "Seni", example: { de: "Er interessiert sich für moderne Kunst.", id: "Dia tertarik pada seni modern." } },
        { article: "das", word: "Foto", plural: "die Foto*s*", genitive: "-s", meaning: "Foto", example: { de: "Kannst du ein Foto von uns machen?", id: "Bisa tolong fotokan kami?" } },
        { article: "die", word: "Kamera", plural: "die Kamera*s*", genitive: "-", meaning: "Kamera", example: { de: "Ich habe eine neue Kamera gekauft.", id: "Saya baru beli kamera baru." } },
        { article: "das", word: "Fest", plural: "die Fest*e*", genitive: "-es", meaning: "Festival", example: { de: "Wir feiern heute ein großes Fest.", id: "Kita merayakan pesta besar hari ini." } },
        { article: "die", word: "Party", plural: "die Party*s*", genitive: "-", meaning: "Pesta", example: { de: "Kommst du zu meiner Party?", id: "Kamu datang ke pestaku kan?" } },
        { article: "das", word: "Geschenk", plural: "die Geschenk*e*", genitive: "-es", meaning: "Hadiah", example: { de: "Ich habe ein Geschenk für dich.", id: "Saya punya hadiah untukmu." } },
        { article: "der", word: "Gast", plural: "die G*ä*st*e*", genitive: "-es", meaning: "Tamu", example: { de: "Wir erwarten heute Abend Gäste.", id: "Kami menantikan kedatangan tamu nanti malam." } },
        { article: "der", word: "Spaß", plural: "-", genitive: "-es", meaning: "Kesenangan", example: { de: "Viel Spaß beim Lernen!", id: "Selamat belajar / semoga menyenangkan!" } },
        { article: "der", word: "Witz", plural: "die Witz*e*", genitive: "-es", meaning: "Lelucon", example: { de: "Er erzählt immer lustige Witze.", id: "Dia selalu menceritakan lelucon lucu." } },
        { article: "der", word: "Grund", plural: "die Gr*ü*nd*e*", genitive: "-es", meaning: "Alasan", example: { de: "Was ist der Grund für deine Verspätung?", id: "Apa alasan keterlambatanmu?" } },
        { article: "die", word: "Meinung", plural: "die Meinung*en*", genitive: "-", meaning: "Pendapat", example: { de: "Meiner Meinung nach ist das richtig.", id: "Menurut pendapatku, itu benar." } },
        { article: "die", word: "Idee", plural: "die Idee*n*", genitive: "-", meaning: "Ide", example: { de: "Das ist eine sehr gute Idee!", id: "Itu adalah ide yang sangat bagus!" } },
        { article: "der", word: "Gedanke", plural: "die Gedanke*n*", genitive: "-ns", meaning: "Pikiran", example: { de: "Ich bin in Gedanken bei dir.", id: "Pikiranku selalu bersamamu." } },
        { article: "die", word: "Lösung", plural: "die Lösung*en*", genitive: "-", meaning: "Solusi", example: { de: "Wir haben eine gute Lösung gefunden.", id: "Kami sudah menemukan solusi yang bagus." } },
        { article: "das", word: "Ziel", plural: "die Ziel*e*", genitive: "-s", meaning: "Tujuan", example: { de: "Sein Ziel ist es, nach Deutschland zu gehen.", id: "Tujuannya adalah pergi ke Jerman." } },
        { article: "der", word: "Erfolg", plural: "die Erfolg*e*", genitive: "-s", meaning: "Kesuksesan", example: { de: "Ich wünsche dir viel Erfolg!", id: "Semoga kamu sukses!" } },
        { article: "die", word: "Lust", plural: "-", genitive: "-", meaning: "Gairah / Minat", example: { de: "Hast du Lust auf einen Kaffee?", id: "Kamu berminat ngopi?" } },
        { article: "die", word: "Angst", plural: "die *Ä*ngst*e*", genitive: "-", meaning: "Takut", example: { de: "Du musst keine Angst haben.", id: "Kamu tidak perlu takut." } },
        { article: "das", word: "Glück", plural: "-", genitive: "-es", meaning: "Beruntung", example: { de: "Viel Glück für deine Prüfung!", id: "Semoga beruntung untuk ujianmu!" } },
        { article: "die", word: "Hilfe", plural: "-", genitive: "-", meaning: "Bantuan", example: { de: "Vielen Dank für deine Hilfe!", id: "Terima kasih banyak atas bantuanmu!" } }
    ]
};